# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('site', models.CharField(choices=[('BLK', 'Блок'), ('CNT', 'Контейнер'), ('SKD', 'СКИД'), ('KKP', 'Сборка станции'), ('DUR', 'Сборка двери'), ('VNT', 'Вентиляционная решётка'), ('EQI', 'Монтаж ОТ оборудования'), ('ELI', 'Монтаж электрооборудования'), ('PIP', 'KVF-трубопровод'), ('GRB', 'ГРБ')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_to_card', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeForWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.SiteType')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOvertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='WorksOnPathcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('pathcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.Pathcard')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, choices=[('BLK', 'Блок'), ('CNT', 'Контейнер'), ('SKD', 'СКИД'), ('KKP', 'Сборка станции'), ('DUR', 'Сборка двери'), ('VNT', 'Вентиляционная решётка'), ('EQI', 'Монтаж ОТ оборудования'), ('ELI', 'Монтаж электрооборудования'), ('PIP', 'KVF-трубопровод'), ('GRB', 'ГРБ')], max_length=3, null=True)),
                ('custom', models.BooleanField(default=False)),
                ('owned_to', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputforms.WorkOvertype')),
                ('stationType', models.ManyToManyField(to='inputforms.StationType')),
            ],
        ),
        migrations.AddField(
            model_name='worksonpathcard',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.WorkType'),
        ),
        migrations.AddField(
            model_name='timeforwork',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.WorkType'),
        ),
        migrations.AddField(
            model_name='station',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.StationType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputforms.Station'),
        ),
    ]
