# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputforms', '0002_pathcard_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathcard',
            name='closed',
        ),
    ]
