# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputforms', '0003_remove_pathcard_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathcard',
            name='door_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='eli_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eli', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='eqi_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqi', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='grb_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grb', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='kkp_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kkp', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='pipe_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipe', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='pathcard',
            name='ventil_site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vent', to='inputforms.SiteType'),
        ),
        migrations.AddField(
            model_name='workovertype',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
