# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputforms', '0004_auto_20160401_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='workovertype',
            name='site',
            field=models.CharField(blank=True, choices=[('BLK', 'Блок'), ('CNT', 'Контейнер'), ('SKD', 'СКИД'), ('KKP', 'Сборка станции'), ('DUR', 'Сборка двери'), ('VNT', 'Вентиляционная решётка'), ('EQI', 'Монтаж ОТ оборудования'), ('ELI', 'Монтаж электрооборудования'), ('PIP', 'KVF-трубопровод'), ('GRB', 'ГРБ')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='door_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='eli_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eli', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='eqi_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqi', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='grb_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grb', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='kkp_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kkp', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='pipe_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipe', to='inputforms.SiteType'),
        ),
        migrations.AlterField(
            model_name='pathcard',
            name='ventil_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vent', to='inputforms.SiteType'),
        ),
    ]
